#!/bin/sh
#删除索引
curl -XDELETE http://localhost:9200/my_index
curl -XPUT http://localhost:9200/my_index -d '
{
    "settings":{
        "index":{
            "analysis":{
                "analyzer":{
                    "path_analyzer":{
                        "tokenizer":"path_hierarchy"
                    },
                    "code_analyzer":{
                        "char_filter":[
                             "my_mapping"
                         ],
                        "filter":[
                            "lowercase"
                        ],
                        "tokenizer":"my_ngram_tokenizer"
                    },
                    "mapping_analyzer":{
                        "char_filter":[
                            "my_mapping"
                        ],
                        "tokenizer":"standard"
                    },
                    "en":{
                        "filter":[
                            "asciifolding",
                            "lowercase",
                            "ourEnglishFilter"
                        ],
                        "tokenizer":"standard"
                    },
                    "pinyin_analyzer":{
                        "filter":[
                            "standard",
                            "nGram"
                        ],
                        "tokenizer":"my_pinyin"
                    }
                },
                "filter":{
                    "ourEnglishFilter":{
                        "type":"kstem"
                    }
                },
                "tokenizer":{
                    "my_pinyin":{
                        "padding_char":"",
                        "type":"pinyin",
                        "first_letter":"prefix"
                    },
                    "my_ngram_tokenizer" : {
                        "type" : "nGram",
                        "min_gram": "2",
                        "max_gram": "3",
                        "token_chars": []
                    }
                },
                "char_filter":{
                    "my_mapping":{
                        "type":"mapping",
                        "mappings":[
                            "免运费 => 0",
                            "免邮 => 0",
                            "包邮 => 0",
                            ", =>  "
                        ]
                    }
                }
            },
            "number_of_shards":"1",
            "number_of_replicas":"0",
            "refresh_interval":"5s"
        }
    }
}
'
#创建索引
curl -XPUT http://localhost:9200/my_index -d '
{
    "settings":{
        "index":{
            "analysis":{
                "analyzer":{
                    "path_analyzer":{
                        "tokenizer":"path_hierarchy"
                    },
                    "my_analyzer":{
                        "char_filter":[
                            "my_mapping"
                        ],
                        "filter":[
                            "lowercase"
                        ],
                        "tokenizer":"standard"
                    },
                    "en":{
                        "filter":[
                            "asciifolding",
                            "lowercase",
                            "ourEnglishFilter"
                        ],
                        "tokenizer":"standard"
                    },
                    "pinyin_analyzer":{
                        "filter":[
                            "standard",
                            "nGram"
                        ],
                        "tokenizer":"my_pinyin"
                    }
                },
                "filter":{
                    "ourEnglishFilter":{
                        "type":"kstem"
                    }
                },
                "tokenizer":{
                    "my_pinyin":{
                        "padding_char":"",
                        "type":"pinyin",
                        "first_letter":"prefix"
                    },
                    "my_ngram_tokenizer" : {
                        "type" : "nGram",
                        "min_gram" : "2",
                        "max_gram" : "3",
                        "token_chars": [ "letter", "whitespace" ]
                    }
                },
                "char_filter":{
                    "my_mapping":{
                        "type":"mapping",
                        "mappings":[
                            "免运费 => 0",
                            "包邮 => 0",
                            ", =>  "
                        ]
                    }
                }
            },
            "number_of_shards":"1",
            "number_of_replicas":"0",
            "refresh_interval":"5s"
        }
    },
    "mappings":{
        "_default_":{
            "dynamic":"strict"
        },
        "my_type":{
            "properties":{
                "code":{
                    "type":"string",
                    "analyzer":"code_analyzer"
                },
                "title":{
                    "type":"string",
                    "store":"yes"
                },
                "content":{
                    "type":"string",
                    "store":"yes"
                },
                "messageList":{
                    "type":"nested",
                    "properties":{
                        "usrKey":{
                            "type":"long",
                            "index":"not_analyzed",
                            "store":"yes"
                        },
                        "message":{
                            "type":"string",
                            "analyzer":"ik_and_word",
                            "store":"yes"
                        },
                        "msgTime":{
                            "type":"date",
                            "format":"yyyy-MM-dd HH:mm:ss",
                            "store":"yes"
                        }
                    }
                },
                "category":{
                    "type":"multi_field",
                    "fields":{
                        "path":{
                            "type":"string",
                            "store":"no",
                            "analyzer":"path_analyzer",
                            "boost":10
                        },
                        "primitive":{
                            "type":"string",
                            "analyzer":"ik_and_word",
                            "store":"yes"
                        }
                    }
                },
                "seq":{
                    "type":"integer",
                    "index":"not_analyzed"
                },
                "author":{
                    "type":"string",
                    "analyzer":"ik_max_word",
                    "store":"yes"
                },
                "newsType":{
                    "type":"multi_field",
                    "fields":{
                        "pingyin":{
                            "type":"string",
                            "store":"no",
                            "term_vector":"with_positions_offsets",
                            "analyzer":"pinyin_analyzer",
                            "boost":10
                        },
                        "primitive":{
                            "type":"string",
                            "store":"yes",
                            "analyzer":"ik_max_word"
                        }
                    }
                }
            }
        }
    }
}
'
#查看文档类型 mapper
curl -XGET http://localhost:9200/my_index/_mapping?pretty
#修改mapper
curl -XPOST "http://localhost:9200/my_index/my_type/_mapping?pretty" -d '
{
    "my_type":{
        "properties":{
            "content":{
                "type":"string"
            }
        }
    }
}
'
curl -XPOST "http://localhost:9200/my_index/my_type/_mapping?pretty" -d '
{
    "my_type":{
        "properties":{
            "messageList":{
                "type":"nested",
                "properties":{
                    "usrKey":{
                        "type":"long",
                        "index":"not_analyzed",
                        "store":"yes"
                    },
                    "message":{
                        "type":"string",
                        "analyzer":"ik_and_word",
                        "store":"yes"
                    },
                    "msgTime":{
                        "type":"date",
                        "format":"yyyy-MM-dd HH:mm:ss",
                        "store":"yes"
                    }
                }
            },
            "category":{
                "type":"multi_field",
                "fields":{
                    "path":{
                        "type":"string",
                        "store":"no",
                        "analyzer":"path_analyzer",
                        "boost":10
                    },
                    "primitive":{
                        "type":"string",
                        "analyzer":"ik_and_word",
                        "store":"yes"
                    }
                }
            }
        }
    }
}
'
curl -XPOST "http://localhost:9200/my_index/my_type/_mapping?pretty" -d '
{
    "my_type":{
        "properties":{
            "seq":{
                "type":"integer",
                "index":"not_analyzed"
            },
            "author":{
                "type":"string",
                "analyzer":"ik_max_word",
                "store":"yes"
            },
            "newsType":{
                "type":"multi_field",
                "fields":{
                    "pingyin":{
                        "type":"string",
                        "store":"no",
                        "term_vector":"with_positions_offsets",
                        "analyzer":"pinyin_analyzer",
                        "boost":10
                    },
                    "primitive":{
                        "type":"string",
                        "store":"yes",
                        "analyzer":"ik_max_word"
                    }
                }
            }
        }
    }
}
'
#修改索引settings
curl -XPUT http://localhost:9200/my_index -d '
{
    "setting": {
        "analysis":{
                "analyzer":{
                    "path_analyzer":{
                        "tokenizer":"path_hierarchy"
                    },
                    "en":{
                        "filter":[
                            "asciifolding",
                            "lowercase",
                            "ourEnglishFilter"
                        ],
                        "tokenizer":"standard"
                    },
                    "pinyin_analyzer":{
                        "filter":[
                            "standard",
                            "nGram"
                        ],
                        "tokenizer":"my_pinyin"
                    }
                },
                "filter":{
                    "ourEnglishFilter":{
                        "type":"kstem"
                    }
                },
                "tokenizer":{
                    "my_pinyin":{
                        "padding_char":"",
                        "type":"pinyin",
                        "first_letter":"prefix"
                    }
                }
            }
    }
}
'